### ISSUE TITLE
Can view panel be disabled?

### ISSUE THREAD

**Issue by yoanhg421** [darodi/kcc#43] opened 2023-03-02 22:03 UTC
With the new Kindle Scribe it would be nice to have panel view disabled. With the large screen size you don't really need it and it's annoying as it activates when trying to skip pages quickly.

**Comment by darodi** [comment] 2023-03-27 21:30
@yoanhg421 

A new beta version with this change is available here
https://github.com/darodi/kcc/releases/tag/v5.6.2b3

Could you try it and give me some feedback?
I don't own a Kindle Scribe.

If it is OK for you, I'll add this change in the main/upstream version

**Comment by yoanhg421** [comment] 2023-03-27 22:54
@darodi Short version. it works great. pages can be flipped fast, no annoying panel. yay

quick side note: When using the "Other profile" the panel is not there but it does make the kindle refresh the page more than usual for some reason. Page flip is not as responsive as with the "KS" profile (I probably did something wrong)

Long Version. I have an M1 mac and the builds have been working fine until Beta3. I don't know what happened. but i get an error now when trying to convert a book, that says NONE, weird. and the program just hangs. works with PDFs and Folders Structured Comics. So I installed windows on a VM to test. Here it keeps saying that 7z is not installed so i couldn't test with a CBZ file there either. but the folder structure worked perfectly on windows as well.

**Comment by darodi** [comment] 2023-03-27 23:45
> quick side note: When using the "Other profile" the panel is not there but it does make the kindle refresh the page more than usual for some reason. Page flip is not as responsive as with the "KS" profile (I probably did something wrong)

In that case, high quality is set to False, with KS profile, it is set to True. That may be the difference.
> 
> Long Version. I have an M1 mac and the builds have been working fine until Beta3. I don't know what happened. but i get an error now when trying to convert a book, that says NONE, weird. and the program just hangs. works with PDFs and Folders Structured Comics. So I installed windows on a VM to test. Here it keeps saying that 7z is not installed so i couldn't test with a CBZ file there either. but the folder structure worked perfectly on windows as well.

On M1 mac, v5.6.2b2 works but not v5.6.2b3?
Could you confirm?
If so, I might know where the problem is and can build a v5.6.2b4 for you to test.

On windows, 7z will be found if you add
`C:\Program Files\7-Zip\` to your Path environment variable.
I'll try to make it work without it.

**Comment by yoanhg421** [comment] 2023-03-28 00:03
Yes. That is the issue with Mac.  v5.6.2b2 works but not v5.6.2b3I can retest windows if you make the change there also. I can also test adding the zip to the path. On the other profile that makes sense.  Because sometimes the page shows crisp and sometimes it apply some type of smoothing filter and that’s when the page refreshes twice.  Would it affect or break a lot of things if you set the high quality to True on the Other Profile? I use it for converting large mangas that still look good a lower resolution in order to get rid of the panel view.  I can also use the PW1/2 or 3/4 but they have the panel enabled.  Sometimes is easier just to type the custom resolution. What do you think ? Sent from my iPhoneOn Mar 27, 2023, at 4:45 PM, darodi ***@***.***> wrote:﻿

quick side note: When using the "Other profile" the panel is not there but it does make the kindle refresh the page more than usual for some reason. Page flip is not as responsive as with the "KS" profile (I probably did something wrong)

In that case, high quality is set to False, with KS profile, it is set to True. That may be the difference.

Long Version. I have an M1 mac and the builds have been working fine until Beta3. I don't know what happened. but i get an error now when trying to convert a book, that says NONE, weird. and the program just hangs. works with PDFs and Folders Structured Comics. So I installed windows on a VM to test. Here it keeps saying that 7z is not installed so i couldn't test with a CBZ file there either. but the folder structure worked perfectly on windows as well.

On M1 mac, v5.6.2b2 works but not v5.6.2b3?
Could you confirm?
If so, I might know where the problem is and can build a v5.6.2b4 for you to test.
On windows, 7z will be found if you add
C:\Program Files\7-Zip\ to your Path environment variable.
I'll try to make it work without it.

**Comment by yoanhg421** [comment] 2023-03-28 04:30
I also noticed that the OTHER is set to isKobo and not to isKindle maybe that has also something to do with the refresh rate. so don't worry about making changes to the OTHER profile. The scribe works well with the panels disabled. I would be nice to be able to save space. But is not super important.

**Comment by yoanhg421** [comment] 2023-03-30 01:34
Do I need to have Kindle Previewer installed in the new beta3?

**Comment by darodi** [comment] 2023-06-10 11:34
closing this
issue created upstream https://github.com/ciromattia/kcc/issues/536

**Closed as completed by darodi** 2023-06-10 11:34 UTC
Labels: enhancement, Awaiting feedback
